export const AUTH_USER = "AUTH_USER";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const TRY_AUTO_LOGIN = "TRY_AUTO_LOGIN";
export const REFRESH_USER_DATA = "REFRESH_USER_DATA";
export const UPDATE_USER = "UPDATE_USER";

export const SET_CONNECTED_TO_INTERNET = "SET_CONNECTED_TO_INTERNET";

export const REPORT_CRIME = "REPORT_CRIME";
export const DO_BACK_SYNC = "DO_BACK_SYNC";
export const REPORT_CRIME_ERROR = "REPORT_CRIME_ERROR";
export const GET_AROUND_DATA = "GET_AROUND_DATA";
export const GET_CITY_DATA = "GET_CITY_DATA";

export const RELATIVE_ERROR = "RELATIVE_ERROR";
export const ADD_RELATIVE = "ADD_RELATIVE";
export const GET_RELATIVE = "GET_RELATIVE";
export const UPDATE_RELATIVE = "UPDATE_RELATIVE";
export const DELETE_RELATIVE = "DELETE_RELATIVE";
