export const AUTH_USER = "AUTH_USER";
export const LOGOUT = "LOGOUT";
export const AUTH_ERROR = "AUTH_ERROR";
export const TRY_AUTO_LOGIN = "TRY_AUTO_LOGIN";
export const REFRESH_USER_DATA = "REFRESH_USER_DATA";
export const UPDATE_USER = "UPDATE_USER";

export const LOADED_DATA = "LOADED_DATA";
export const SET_CONNECTED_TO_INTERNET = "SET_CONNECTED_TO_INTERNET";

export const REPORT_CRIME = "REPORT_CRIME";
export const DO_BACK_SYNC = "DO_BACK_SYNC";
export const REPORT_CRIME_ERROR = "REPORT_CRIME_ERROR";
export const GET_AROUND_DATA = "GET_AROUND_DATA";
export const GET_CITY_DATA = "GET_CITY_DATA";

export const RELATIVE_ERROR = "RELATIVE_ERROR";
export const ADD_RELATIVE = "ADD_RELATIVE";
export const GET_RELATIVE = "GET_RELATIVE";
export const UPDATE_RELATIVE = "UPDATE_RELATIVE";
export const DELETE_RELATIVE = "DELETE_RELATIVE";

export const SEEN_ALERT = "SEEN_ALERT";
export const SEEN_ALERT_POLICE = "SEEN_ALERT_POLICE";

export const UPDATE_NOTIFICATION_SETTING = "UPDATE_NOTIFICATION_SETTING";

export const POLICE_AUTH = "POLICE_AUTH";
export const POLICE_LOGOUT = "POLICE_LOGOUT";
export const SET_IS_POLICE = "SET_IS_POLICE";
export const REFRESH_POLICE_DATA = "REFRESH_POLICE_DATA";
